Add wait for nodepool
ionos-enterprise/ionos-enterprise-sdk-go pull request #82
Opened 2020-08-28 06:42 UTC by schegi

* Add some convenient methods for actively waiting for K8s resources cluster and nodepool the reach a specified state.
* Types K8S resource state constants

2020-09-02 14:20 UTC, avorima requested changes
Needs rebase after https://github.com/ionos-enterprise/ionos-enterprise-sdk-go/pull/80 is merged

2020-09-02 14:20 UTC, avorima commented on go.mod
> +	k8s.io/apimachinery v0.18.6
No, please don't import apimachinery here. I see you using one function from there, just re-implement it or write an equivalent function.

2020-09-02 14:20 UTC, avorima commented on k8s.go
> +type KubernetesClusterNodePoolState string
Remove this type

2020-09-02 14:20 UTC, avorima commented on k8s.go
> +type KubernetesNodeState string
Remove this type

2020-09-02 14:20 UTC, avorima commented on k8s.go
> +	timeout, interval time.Duration) (err error) {
The error returned by this function should include which state was polled

2020-09-02 14:20 UTC, avorima commented on k8s.go
> +	return wait.PollImmediate(interval, timeout, func() (done bool, err error) {
These named return values also are not needed

2020-09-02 14:20 UTC, avorima commented on k8s.go
> +		return np != nil && np.Metadata != nil && np.Metadata.State == string(state), err
Return `nil` instead of `err` here

2020-09-02 14:20 UTC, avorima commented on k8s.go
> +	clusterID string, state KubernetesClusterNodePoolState, timeout, interval time.Duration) (err error) {
Same remarks as above

2020-09-03 12:27 UTC, avorima requested changes
Please run `go mod tidy` and `goimports`.

2020-09-03 12:27 UTC, avorima commented on k8s.go
> +		return fmt.Errorf("error waiting for nodepool state %s [%w]", state, err)
Please use `: %w` for wraps

2020-09-09 13:05 UTC, avorima approved these changes
LGTM

2020-10-07 16:44 UTC, pennycoders approved these changes

2020-10-07 16:46 UTC, merged